### ISSUE TITLE
PDS App Bar does not work if it's included after the DOM loads

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-PDS/pds-wds-web#10]
**Describe the bug**
The `document.addEventListener("DOMContentLoaded")` event never gets called (and therefore the app bar never gets created) if this event handler loads after the main page has initialized.

**To Reproduce**
Some sites, such as the current PDS Atlas, injects site-wide header information through a script tag in each page's body.
1. Add the pds app bar script by adding a script tag via javascript after the page loads.

**Expected behavior**
The pds app bar should work on pages that have already initialized.

**Version of Software Used** 
91ba04a8b0a6da2303b7af2eb75446c3c7285612

**Possible Solution**
Perhaps adding:
```
if (document.readyState != "loading") PDS_App_Bar();
else
    document.addEventListener("DOMContentLoaded", function () {
      PDS_App_Bar();
    });
```
after the `PDS_App_Bar` is created (`PDS_App_Bar` is defined within a function so its scope won't be global until it runs)

**Comment by jordanpadams** [comment]
@tariqksoliman since we don't have a site that does this, would you mind testing this change out for us? it would save us exponential amounts of headache trying to figure out how to test it :-)

**Comment by jordanpadams** [comment]
@tariqksoliman if you follow the installation guide step 2, and download and install the package locally, you should be able to inject this code you referenced and see if it works. thanks!

https://github.com/NASA-PDS/pds-wds-web/tree/master/app-bar#installation

**Comment by c-suh** [comment]
Hi @tariqksoliman, the fix has been merged into the master branch and deployed to the [PDS site](https://pds.nasa.gov/).
