### ISSUE TITLE
Show screenshot of app-bar in README

### ISSUE THREAD

**Issue by riverma** [NASA-PDS/pds-wds-web#12]
**Is your feature request related to a problem? Please describe.**
It's difficult to visualize the app-bar from the textual description given in the [README](https://github.com/NASA-PDS/pds-wds-web/tree/master/app-bar#pds-app-bar). People trying to understand the integration of an app-bar into their websites would benefit from a visual example, and would probably help drive adoption and prep work (if needed). 

**Describe the solution you'd like**
- Include screenshot of latest app bar in the [README](https://github.com/NASA-PDS/pds-wds-web/tree/master/app-bar#pds-app-bar)
- Include numerical annotations explaining different parts of the app bar, and which areas are to be customized and how

**Describe alternatives you've considered**
N/A

**Additional context**
Personally have seen the app-bar and it looks good, though others who haven't may not have that benefit.

**Comment by jordanpadams** [comment]
@riverma apologies for the confusion. we will definitely get on this.

see here: https://pds.nasa.gov
