### ISSUE TITLE
App Bar breaks facet selection on Photojournal Beta

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-PDS/pds-wds-web#15]
**Describe the bug**
The App Bar is assigning a global event and making the false assumption that e.composedPath is always a function. This has the potential to break many sites.  

**To Reproduce**
1. Visit https://photojournal.jpl.nasa.gov/beta
2. Change the value in one of the dropdowns at the top.
3. The facet cannot be changed.
4. Open the dev console and see*:

```
Uncaught TypeError: e.composedPath is not a function
    at HTMLBodyElement.document.body.onclick (pds-app-bar.js:193)
```
*This is pulling from the EN host App Bar

**Expected behavior**
The App Bar does not interfere with any other site functionalities

**Comment by jordanpadams** [comment]
thanks for catching this @tariqksoliman ! we will look into this. in the meantime, we at EN are more interested in the pds-imaging website for the time being.
