### ISSUE TITLE
Fix issues with app bar dropdown outline on specific browsers / OSes

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-web#27]
## 🐛 Describe the bug

Per https://github.com/NASA-PDS/pds-wds-web/pull/26, some issues have been identified on various browsers:

- [ ] On windows Chrome, the outline is white
- [ ] Firefox and Edge seem to not have an outline
- [ ] MacOS Safari the outline is blue and it seemed to 'stick' so on first dropdown after select of nav item, i could see the outline
- [ ] IOS safari behaves like MacOS safari

## Browser / OS Versions
TBD from customer

**Comment by jordanpadams** [comment]
Noticed this on PPI website using Chrome on Mac (on mouseover)

**Comment by jordanpadams** [comment]
<img width="616" alt="Screen Shot 2021-09-08 at 8 48 15 AM" src="https://user-images.githubusercontent.com/33492486/132542176-d39aea49-7453-41e9-90ec-419990f54f23.png">

**Comment by c-suh** [comment]
Regarding the browser-specific changes: with preliminary testing, I'm not seeing issues on Firefox, Chrome, or MacOS Safari. Am finding out about Edge and IOS Safari.

---

Regarding the 2 issues seen on PPI which @jordanpadams put screenshots for above:
1. [outline color and shape](https://github.com/NASA-PDS/pds-wds-web/issues/27#issuecomment-915355257) - this was addressed in https://github.com/NASA-PDS/pds-wds-web/pull/26, specifically in [these lines](https://github.com/NASA-PDS/pds-wds-web/pull/26/files#r845452474)
2. [background color](https://github.com/NASA-PDS/pds-wds-web/issues/27#issuecomment-915356828) - I've just pushed a change to new branch, [issue-27](https://github.com/NASA-PDS/pds-wds-web/tree/issue-27)

**NOTE**: PPI isn't sourcing the app bar from the PDS site but has it deployed locally.

**Comment by c-suh** [comment]
Mostly redundant update:

Re-reading PR #26 mentioned in the description, it appears that dstopp was seeing the issues mentioned above, even after the merge. However, I haven't been able to replicate the issues.
Regarding the two issues Jordan found above regarding the [element borders](https://github.com/NASA-PDS/pds-wds-web/issues/27#issuecomment-915355257) and [link background-color](https://github.com/NASA-PDS/pds-wds-web/issues/27#issuecomment-915356828), the former will be fixed if they pull the new code or just reference the PDS files and the latter is in PR https://github.com/NASA-PDS/pds-wds-web/pull/29.
The PR also incorporates two other node-specific styles and general improvements on focus and hover (there is no issue or ticket for these).
I will be bringing up the PR and a possible release for this repo in today's PDS meeting.

@jordanpadams a note about the nodes, 4 of them have it deployed locally (opposed to referencing the JS and CSS files from the PDS site). Will you be reaching out to them? 
- GEO at https://pds-geosciences.wustl.edu/
- NAIF at https://naif.jpl.nasa.gov/naif/
- PPI at https://pds-ppi.igpp.ucla.edu/
- RMS at https://pds-rings.seti.org/

**Comment by jordanpadams** [comment]
Issues identified have either all been fixed or they need to source our online files

**Comment by jordanpadams** [comment]
@jordanpadams to create new tickets

**Comment by c-suh** [comment]
@jordanpadams the changes are live at https://pds.nasa.gov/.
