### ISSUE TITLE
App Bar causes usability issues on mobile

### ISSUE THREAD

**Issue by mdrum** [NASA-PDS/pds-wds-web#9]
**Describe the bug**
The app bar is currently deployed at https://sbn.psi.edu/pds, but once we did that we got a usability error report from Google search console. I have verified the findings reported:
1. **Content is wider than screen**: on narrow width screens, the side-scroll bar appears
2. **Clickable elements too close together**: no further details on this, but I would assume it is referring to the drop-down menu next to the information icon?

**To Reproduce**
1. Go to https://sbn.psi.edu/pds on a mobile device, or using Chrome dev tools on iPhone X
2. Scroll horizontally
3. Note whitespace on the right-hand side

**Expected behavior**
Page should not be wider than its content, and users should not be able to scroll horizontally.
Buttons should be approx. 48px wide

** Version of Software Used**
[Currently-deployed script](https://pds.nasa.gov/pds-app-bar/pds-app-bar.js) as of 10/8/20 

**Test Data / Additional context**
I have verified that removing the app bar fixes these issues, so the problem is constrained there

**Desktop (please complete the following information):**
 - OS: iOS, macOS
 - Browser: Safari, Chrome

**Applicable requirements**
Screen width 375px (iPhone)

**Comment by jordanpadams** [comment]
thanks @mdrum we will take a look

**Comment by c-suh** [comment]
I will address the issue of the horizontal scroll and whitespace on the right-hand side. @edwardbarraza, how would you like to handle the placement and arrangement of the clickable elements?

**Comment by edwardbarraza** [comment]
@c-suh Google sometimes flags these for buttons and navigational links, specifically referring to a mobile use case. Users can't easily tap a desired element with their finger without also tapping a neighboring element. We should try:

-  increasing the space between the PDS Information icon and the Find a Node dropdown, and ensure the space is not proportional to screen width. 
- increasing the PDS Info info (up to 17x17) 

I've made some changes here: https://www.figma.com/file/Sr1NxgRuxhTfHNncuCMV7y/?node-id=580%3A0

**Comment by c-suh** [comment]
@edwardbarraza 

> - increasing the space between the PDS Information icon and the Find a Node dropdown, and ensure the space is not proportional to screen width.

- I will increase the space between the PDS Information icon and link to Find a Node dropdown to make the elements more easily tappable. 
- Please note that the spacing was not proportional to screen width to begin with; widths and spacings were (still are, it seems) fixed values regardless of screen width, starting from the leftmost element, with no specification for the space from the rightmost element to the right edge of the screen.

> - increasing the PDS Info info (up to 17x17)

- PDS Info _icon_? I have just verified that it already is 17x17
- PDS Info _information-text_? I agree the sizing/placement should be changed, and part of that is shoddy implementation on my part. I can address this but leave the values for you to determine, although I do think that 17x17 is too small for this element. Just a thought :] However, this would be covered by specifications by breakpoint, which you've mentioned is a work in progress. Do we have an open issue for this (the aesthetics, not usability, of the app bar in mobile format)?

**Comment by edwardbarraza** [comment]
PDS info _icon_ @c-suh ! That's what I meant. 
Regarding the icon size, let's bump up 3px to make it a 20x20. I tried 24x24 (default icon size in our system) and it fits too tightly in the app bar (is the app bar now 32px, consistent with that of Eddie and Tariq's?)

**Comment by tloubrieu-jpl** [comment]
@c-suh  will fix what is easy to fix and report to @mdrum about the more difficult things to fix that we will not be able to work on immediatly.

**Comment by c-suh** [comment]
Hi @mdrum, some notes:
- Regarding the spacing of clickable elements, after the code has been merged (or you can test with branch [issue-09](https://github.com/NASA-PDS/pds-wds-web/tree/issue-09)), it will likely need to be tested again to see if we've added sufficient space, specifically between the information icon and drop-down menu.
- Regarding the horizontal scroll/whitespace, there was an element in the app bar which was extending past the screen, and I have addressed that. However, I still see this problem even after removing the app-bar from your test deployment site, which leads me to think that this is not the only guilty party?

**Comment by mdrum** [comment]
@c-suh Thank you! 
That site I linked is our live archive site, and it's directly pulling from https://pds.nasa.gov/pds-app-bar/pds-app-bar.js. If you deploy the fixes there, it should trickle down to our site as well. I'll be on vacation next week but if you end up deploying changes, that shouldn't cause any issues.

I'm not sure what you mean about the horizontal space. When I enter Chrome developer tools on https://sbn.psi.edu/pds/ and delete the app-bar element, the extra whitespace disappears. Are you seeing different behavior?

**Comment by c-suh** [comment]
@mdrum, interestingly, I _am_ seeing a different behavior! Here's a screenshot:

![pds-app-bar-whitespace](https://user-images.githubusercontent.com/18314609/97060687-fa885780-1548-11eb-9df0-929a4e5724ad.jpg)

This happens in Chrome and Safari for me. Firefox does not show a whitespace to begin with, nor does my Android phone.

Re: the other changes, once the PR is approved, I will deploy the updates to pds.nasa.gov and and test sbn.psi.edu/pds with Google's mobile-friendly test tool.

**Comment by c-suh** [comment]
@mdrum the changes are deployed to the PDS [website](https://pds.nasa.gov/), and https://sbn.psi.edu/pds now passes Google's mobile-friendly test!

However, there are now two pds-app-bars on your page. I took a quick look and suspect it's from the SBN script, specifically from the function call for the app bar right before its javascript file is appended to the body of the page. (You or your programmers probably have that in there due to an initial error on my part which has since been addressed. Sorry!) Would you mind having that line removed to see if it fixes the problem?

**Comment by mdrum** [comment]
@c-suh Thanks! I've addressed that issue on our site, one app bar now appears, and I've also verified the fixes.
